### ISSUE TITLE
As a deployer I want to be able to run Open edX in Kubernetes/Openshift on unprivileged containers

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#13]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

- Tutor core can run in unprivileged mode as of Maple
- Running the other plugins in this mode should be a straightforward, fast follow.

Currently, some Tutor containers are run as root, which may be impossible for security reasons in some environments. These containers should switch to unprivileged users, which may cause compatibility issues with bind-mounted volumes for the local installation.

Note: we mostly need to get rid of bind-mounted volumes. This will entail migrating to object storage by default.

**Comment by regisb** [comment]
A lot of progress has been made on that front. Since Maple, Tutor runs in Kubernetes with unprivileged containers. As far as I know, there are still some issues with Openshift: https://discuss.overhang.io/t/openshift-4-6-k8s-1-19-install/2169
It's difficult for me to resolve this problem without access to an actual Openshift cluster with the same permissions.

**Comment by kdmccormick** [comment]
@regisb I'm going to close this because I don't think it's within the scope of this project. Feel free to move it elsewhere if it's something you wanted to keep open for any reason.
