### ISSUE TITLE
How could Tutor better provide error logging & stack traces?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#15]
## Context

When I develop on Open edX, I sometimes stumble on errors that are hard to debug. To understand these issues, I need to have access to the error stacktrace. Currently, I do this by bind-mounting the IDA repository or virtual environment, then add a break point (`import pdb; pdb.set_trace()`) to the code and run the app in dev mode (`./manage.py runserver`). This is all very inconvenient. Instead, what we could do is to collect the error logs and stacktraces using tools such as Sentry. Sentry could be added to Tutor as a plugin.

Current state of error logs & stacktraces:
- "Currently this is resolved with a very small hack."  https://discuss.openedx.org/t/convenient-stacktrace-formatter-for-django-logging/5887
- Hard to do interservice traces, similar to what you might get from, say, Datadog or Newrelic
- Currently Regis is dropping stacktraces to a specified directory on the host filesystem
- In VS code you can connect to a remote container and add breakpoints

Note: there are different ways to approach this. Thus, the time estimate can vary. 

## Acceptance

Propose solution for improving the state of error tracking (or, propose that we do nothing).

**Comment by regisb** [comment]
At the time, what I had in mind was to offer a self-hosted [Sentry](https://sentry.io/) stack to collect stacktraces across the entire Open edX platform, both for frontends and backends. Turns out that in 2022, it's incredibly difficult to run Sentry ([docker-compose.yml](https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml)). Maybe that we could use an alternative piece of software such as [Glitchtip](https://glitchtip.com/).

**Comment by kdmccormick** [comment]
Personally, I'd need to do some research in order to begin implementing anything, so I've turned this issue into a question/discovery item.

**Comment by kdmccormick** [comment]
I'm not seeing any acute need for this.
