### ISSUE TITLE
As a developer I want to run Code Jail in Tutor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#19]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

eduNEXT has completed the work, it will be included with Maple.  eduNEXT has committed to maintain based on standards that Regis established.
   We don't yet have a list of supported plugins, Regis would like to add this to the docs.
Tutor support Code Jail for sandboxing instructor and learner python code

**Comment by regisb** [comment]
Also tracked here: https://github.com/overhangio/tutor/issues/284

The problem is that the [tutor plugin](https://github.com/eduNEXT/tutor-contrib-codejail/) was not upgraded to Maple: https://github.com/eduNEXT/tutor-contrib-codejail/issues/4 :fearful: 
https://github.com/eduNEXT/tutor-contrib-codejail/blob/026d74f981d9fa2b19dbad25550558f41ae5cbde/setup.py#L42

We must do a better job to incentivize developers of 3rd-party plugins to keep up with the pace of named releases.

**Comment by kdmccormick** [comment]
Nice.
> We must do a better job to incentivize developers of 3rd-party plugins to keep up with the pace of named releases.

At some point, let's brainstorm on that here: https://github.com/overhangio/2u-tutor-adoption/issues/44
