### ISSUE TITLE
Turn importdemocourse into an ordinary script

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#31]
## Context

`tutor <mode> importdemocourse` is implemented a special command in the core Tutor API.

Would it make sense to make into an ordinary, templated shell script that users could call with ~`tutor <mode> exec cms scripts/importdemocourse`~ `tutor <mode> run cms scripts/importdemocourse`?

## Acceptance

* Move importdemocourse to a shell script in the CMS container.
* Make `tutor <mode> importdemocourse` an alias of `tutor <mode> run cms scripts/importdemocourse`. Announce the former's deprecation on the Tutor forums and raise a deprecation warning when it is used.
* Update Tutor's docs to reference `tutor <mode> run cms scripts/importdemocourse`.
* Remove code paths from Tutor that are unused after this refactoring.

**Comment by regisb** [comment]
That would make a lot of sense, yes. This would be a minor change that would drastically simplify the codebase, I have avoided doing so before but can't remember why I didn't eventually proceed -- probably by fear of breaking the API.

Note that `run` is preferred over `exec`, because we need to define the `DJANGO_SETTINGS_MODULE` environment variable. When we `exec` environment variables are undefined -- and this is actually one of the challenges of running ad-hoc jobs on Kubernetes, because `exec` is all we got.

**Comment by kdmccormick** [comment]
Nice, I will file this as a piece of tech debt we could tackle. Seems like it'd also be a prereq of LMS/CMS being extracted, if we decide to do that.

If compatibility were cruicial, we could keep the old form around by aliasing it to the new one, while still removing the old internal implemenation.

Good to know about run vs. exec.

**Comment by kdmccormick** [comment]
Handled by https://github.com/openedx/wg-developer-experience/issues/75
